### ISSUE TITLE
Amount display styles

### ISSUE THREAD

**Issue by i5hi** [StackmateNetwork/the-stackmate#14]
### 1. Upto 1 million sats, use comma to separate every thousandth unit and represent as `sats`

100 sats
1,000 sats
10,000 sats

100,000 sats

### 2. Upto 1 BTC, represent as `million sats`and round to 4 digits.

1.0000 million sats
10.0000 million sats
100.0000 million sats

### 3. At 1 BTC, represent values as BTC first, always showing  8 decimal places.

1.00000000 BTC 
21.00000000 BTC
900.00000000 BTC

# Balances

Use the above notation as default.

# Transaction History

Use the above notation in short views. In detailed views, use complete satoshi or BTC value.

# Send

Use complete satoshi or BTC value.

For satoshi values, only follow the first notation.

**Comment by i5hi** [comment]
Two functions in `pkg`? called 

`String formatSatsValue(int)`: does 1, 2 & 3 

`String formatBTCValue(float): does only 3`

These can be used in all the ui screens just before displaying.

**Comment by yashwanthambati** [comment]
Done 1 task
