### ISSUE TITLE
Send Amount Bug

### ISSUE THREAD

**Issue by i5hi** [StackmateNetwork/the-stackmate#27]
Send amount BTC value doesn't update after 3 digits of sats value is entered.
For example while typing 50,090 sats

Upto 500 the BTC value reflects as 0.00000500 then when we type the 4th digit 9, the BTC value resets to 0.00000000

**Comment by yashwanthambati** [comment]
removed thousand formatter for send amount,it should work now

**Comment by i5hi** [comment]
We need the Thousands Formatter is required to show comma after ever 000


This is fixed I think now by making the cubit use replace (',', '')

**Comment by i5hi** [comment]
Will be better if we use another widget where we can use the same formatter we have everywhere else which uses space instead of comma.
