### ISSUE TITLE
/lib/x86_64/libtor.so: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by ag-0214** [StackmateNetwork/the-stackmate#52]
Hi,
I am trying to start to on android using UtopicTorOnionProxy.startTor() and I am getting this error. Is there anything I need to do
E/TorNativeLoader(18204): /data/app/~~5LvdEY2hDiPfuUNCXqT2LA==/{my package}-D4ocGlpeQc13AFEzgJUvjw==/lib/x86_64/libtor.so: open failed: EACCES (Permission denied)
D/CompatibilityChangeReporter(18204): Compat change id reported: 147798919; UID 10183; state: ENABLED
W/TorInstaller(18204): Failed to setup tor. No tor executable installed
W/System.err(18204): java.io.IOException: Failed to Failed to setup tor. No tor executable installed
W/System.err(18204): 	at ru.utopicnarwhal.utopic_tor_onion_proxy.thali_sources.android.AndroidTorInstaller.setup(AndroidTorInstaller.java:90)
W/System.err(18204): 	at ru.utopicnarwhal.utopic_tor_onion_proxy.thali_sources.OnionProxyManager.setup(OnionProxyManager.java:611)
W/System.err(18204): 	at ru.utopicnarwhal.utopic_tor_onion_proxy.UtopicTorOnionProxyPlugin.startTor(UtopicTorOnionProxyPlugin.java:125)
W/System.err(18204): 	at ru.utopicnarwhal.utopic_tor_onion_proxy.UtopicTorOnionProxyPlugin.onMethodCall(UtopicTorOnionProxyPlugin.java:98)
W/System.err(18204): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(18204): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(18204): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/System.err(18204): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(18204): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(18204): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(18204): 	at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(18204): 	at android.os.Looper.loop(Looper.java:288)
W/System.err(18204): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
W/System.err(18204): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18204): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err(18204): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/flutter (18204): type 'String' is not a subtype of type 'StackTrace' in type cast

Regards.
AG

**Comment by i5hi** [comment]
Are you using it out of the-stackmate? 

Could you show me exactly how you are using it?

**Comment by ag-0214** [comment]
Hi,
I use a different state management from the one in the wallet so I just thought to replace that with the one I am using but still archiving the same results. 

below is a method extracted from lib/cubit/tor.dart that  I am calling and its giving that message

  Future<void> start() async {
    try {
      final result = await InternetAddress.lookup('google.com');
      if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
        final port = await UtopicTorOnionProxy.startTor();
        _currentTorState = currentTorState.copyWith(
            socks5Port: port!,
            errConnection: '',
            isRunning: true,
            isConnected: true,
          );
      } else {
        _currentTorState = currentTorState.copyWith(
            isRunning: false,
            errConnection: 'Not Connected To The Internet.',
          );
      }
    } catch (e) {
      _currentTorState = currentTorState.copyWith(
          isRunning: false,
          errConnection: e.toString(),
        );
      _loggerService.logException(e, 'Tor.start', '');
      return;
    }
  }

Then I call the above method when I am loading my first view

regards.

**Comment by i5hi** [comment]
Have you added all the changes to AndroidManifest and build.gradle that is required by utpoics library?

**Comment by i5hi** [comment]
W/TorInstaller(18204): Failed to setup tor. No tor executable installed

Its not able to find the tor binary that comes with the lib.

Have you run flutter pub get?

**Comment by i5hi** [comment]
https://pub.dev/packages/utopic_tor_onion_proxy

Revisit the instructions here.

**Comment by ag-0214** [comment]
Hi,
Thanks very much. I had added all and started to have the compile error so had removed them. Now i started adding one by one and I solved the issue by adding only this line in my manifest and it worked.
android:extractNativeLibs="true"

regards

**Comment by i5hi** [comment]
Awesome!
