### ISSUE TITLE
Select network fee error

### ISSUE THREAD

**Issue by ag-0214** [StackmateNetwork/the-stackmate#53]
I am trying to use your wallet, I have 100000 Sats in my wallet now when I try to send 50000 sats to another wallet, when it gets to the stage of selecting network fee it gives the following error. If I click back the where I to the screen I entered amount it will display message instance of SMError . For smaller amounts like 50 sats it doesnt give an error but there ont be any fee to select so cant proceed

[log] 'package:flutter/src/material/slider.dart': Failed assertion: line 147 pos 15: 'value >= min && value <= max': is not true.
      #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
      #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
      #2      new Slider (package:flutter/src/material/slider.dart:147:15)
      #3      _SelectFeeState.build (package:sats/ui/component/Send/SelectFee.dart:118:13)
      #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
      #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
      #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
      #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
      #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
      #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
      #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
      #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
      #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
      #13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
      #14     _rootRun (dart:async/zone.dart:1426:13)
      #15     _CustomZone.run (dart:async/zone.dart:1328:19)
      #16     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
      #17     _invoke (dart:ui/hooks.dart:151:10)
      #18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
      #19     _drawFrame (dart:ui/hooks.dart:115:31)
regards
AG

**Comment by i5hi** [comment]
This happens often on Testnet because the network fee is always 1.0 sat/byte.

It's breaking because the fee slider values require a min , max, and value and they don't meet the conditions.

Those values get set in the slider.dart file based on the feeCubit values.

**Comment by i5hi** [comment]
You can temporarily fix this by hard coding the min value to 1. 

This will temporarily create another bug where if you use low levels on the slider the fee will be too low and it will break on the next step giving a min relay fee error.

**Comment by i5hi** [comment]
Also, generally the way we do fees requires some more attention.

Its very naive right now. 

1 conf network estimate for **fast** 
value/2 for **medium** 
1 sat/byte for **slow**

in this error
```[log] 'package:flutter/src/material/slider.dart': Failed assertion: line 147 pos 15: 'value >= min && value <= max': is not true.```

We use medium fee for the `value` which ends up being 0.5 while min and max are both 1.

**Comment by i5hi** [comment]
This will be fixed in the next release by the 28th.
