### ISSUE TITLE
Changing to testnet bug

### ISSUE THREAD

**Issue by yashwanthambati** [StackmateNetwork/the-stackmate#58]
Changing from mainnet to testnet from settings

- Toggle to testnet does not check for master key and errors.
- if there is no master key/wallets for testnet,it throws an error on homepage

**Comment by i5hi** [comment]
Okay. We should conduct a test for master key and redirect to New from Seed or Import - similar to the check made on app start up.

**Comment by yashwanthambati** [comment]
Resolved.
