### ISSUE TITLE
Better Error Handling

### ISSUE THREAD

**Issue by i5hi** [StackmateNetwork/the-stackmate#68]

**Comment by i5hi** [comment]
All errors must be properly handled and meaningfully passed to the user.

**Comment by yashwanthambati** [comment]
Displayed error messages on bottom

**Comment by i5hi** [comment]
> Displayed error messages on bottom 

I am not able to find the error component you made.

**Comment by i5hi** [comment]
It should be under ui/component/common

**Comment by i5hi** [comment]
Okay! Progress!!

So the ErrorHandler SnackBar should always be called within a BlocListener NEVER inside a BlocBuilder.

This means errors should always be cleared within cubits when state is updated.

**Comment by i5hi** [comment]
Looking good!

Closing this issue. We now have a process for error handling. 

All errors covered for NewWallet screens and Send.
