### ISSUE TITLE
Move Private Keys to Secure Storage

### ISSUE THREAD

**Issue by i5hi** [StackmateNetwork/the-stackmate#90]
Currently only the database encryption key is stored in secure storage and private key data is stored in hive. 

Private Key data must move to secure storage and accessed only when required.

**Comment by i5hi** [comment]
Currently, private keys are stored in two models:

- master:
This is the master key (primary key) stored as a bip39 string as well as a bip32 xprv

*Only this model should be stored in secure storage*

- wallet
In this model, the `descriptor` field currently also contains private keys for this specific wallet in the bip32 xprv format.

For watch-only wallets, the `descriptor` will only contain xpubs. This should be the standard.

All wallets will be watch-only and when required to sign, it will get the master from secure storage, derive the required child key for the wallet (based on the path in the descriptor), and convert the public descriptor to its private version and use that with stackmate-core (bdk).

The private descriptor is never stored even in the cubit state.

NOTE: Currently we identify a watch-only wallet based on whether the `descriptor` is only public. We should make a new field called `isWatcher` of type bool to clearly indicate this.

**Comment by i5hi** [comment]
We can actually preserve the masterKey model and store it as a stringified JSON in secure storage. This will make it so that we won't have to change much logic in masterKey model usage.

**Comment by yashwanthambati** [comment]
Sure. https://stackoverflow.com/questions/66253148/store-data-model-into-flutter-secure-storage?rq=2

**Comment by yshwanth** [comment]
Completed
